// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Kivora Digital S.L.

package app_test

import (
	"context"
	"errors"
	"strings"
	"testing"
	"time"

	"github.com/kivoradigital/wspace/internal/app"
	"github.com/kivoradigital/wspace/internal/domain"
	"github.com/kivoradigital/wspace/internal/messages"
	"github.com/kivoradigital/wspace/internal/ports"
	"github.com/kivoradigital/wspace/internal/ports/portstest"
)

const adoptRoot = domain.Path("/abs/workspaces")

// adoptFixture is a context "work" whose WorkspacesRoot already holds
// directories created by the legacy bash tool.
type adoptFixture struct {
	fs    *portstest.FakeFS
	store *portstest.FakeConfigStore
	git   *portstest.FakeGit
	ctx   domain.Context
}

func newAdoptFixture(t *testing.T) *adoptFixture {
	t.Helper()
	fs := portstest.NewFakeFS(t)
	if err := fs.MkdirAll(adoptRoot); err != nil {
		t.Fatal(err)
	}
	base := domain.BranchName("main")
	return &adoptFixture{
		fs:    fs,
		store: portstest.NewFakeConfigStore(),
		git:   portstest.NewFakeGit(),
		ctx: domain.Context{
			Name:           "work",
			WorkspacesRoot: adoptRoot,
			ProjectsRoot:   "/abs/projects",
			Defaults:       domain.Options{BaseBranch: &base},
			Projects: []domain.Project{
				{Key: "Some.Api", SourceDir: "/abs/projects/Some.Api"},
				{Key: "web", SourceDir: "/elsewhere/Some.Web"},
			},
		},
	}
}

// legacy writes "<root>/<name>/.ws/workspace.conf" plus one folder per alias.
func (f *adoptFixture) legacy(t *testing.T, name, conf string, aliases ...string) domain.Path {
	t.Helper()
	root := adoptRoot.Join(name)
	if err := f.fs.MkdirAll(root.Join(".ws")); err != nil {
		t.Fatal(err)
	}
	for _, a := range aliases {
		if err := f.fs.MkdirAll(root.Join(a)); err != nil {
			t.Fatal(err)
		}
	}
	if err := f.fs.WriteFile(root.Join(".ws", "workspace.conf"), []byte(conf), 0o644); err != nil {
		t.Fatal(err)
	}
	return root
}

func (f *adoptFixture) run(t *testing.T) app.AdoptLegacyWorkspacesResult {
	t.Helper()
	res, err := app.AdoptLegacyWorkspaces(context.Background(), app.Deps{Store: f.store, Git: f.git, FS: f.fs}, app.AdoptLegacyWorkspacesInput{Context: f.ctx})
	if err != nil {
		t.Fatalf("AdoptLegacyWorkspaces: %v", err)
	}
	return res
}

const demoConf = `# ws workspace manifest - regenerated by ws, edit with ws add/rm
name = demo
created = 2025-03-04T05:06:07Z
projects_root = /abs/projects
base_branch = develop
branch = feature/demo
copy_env = yes

[repos]
api|Some.Api|feature/demo
web|Some.Web|
`

func TestAdoptLegacyWorkspaces_WritesAManifestAndNeverTouchesTheLegacyFiles(t *testing.T) {
	f := newAdoptFixture(t)
	root := f.legacy(t, "demo", demoConf, "api", "web")
	f.fs.Writes = nil

	res := f.run(t)

	if len(res.Skipped) != 0 {
		t.Fatalf("Skipped = %+v, want none", res.Skipped)
	}
	if len(res.Adopted) != 1 || res.Adopted[0].Name != "demo" || res.Adopted[0].Root != root {
		t.Fatalf("Adopted = %+v, want demo at %s", res.Adopted, root)
	}

	m, err := f.store.LoadManifest(context.Background(), root)
	if err != nil {
		t.Fatalf("LoadManifest: %v", err)
	}
	ws := m.Workspace
	if m.SchemaVersion != 1 || ws.Name != "demo" || ws.Root != root || ws.Context != "work" || ws.Branch != "feature/demo" {
		t.Errorf("manifest workspace = %+v", ws)
	}
	if !ws.Created.Equal(time.Date(2025, 3, 4, 5, 6, 7, 0, time.UTC)) {
		t.Errorf("Created = %v", ws.Created)
	}
	if ws.Options.BaseBranch == nil || *ws.Options.BaseBranch != "develop" {
		t.Errorf("Options.BaseBranch = %v, want develop (from the legacy manifest)", ws.Options.BaseBranch)
	}
	if ws.Options.CopyEnv == nil || !*ws.Options.CopyEnv {
		t.Errorf("Options.CopyEnv = %v, want true", ws.Options.CopyEnv)
	}
	want := []domain.RepoEntry{
		{Alias: "api", Project: "Some.Api", SourceDir: "/abs/projects/Some.Api", Branch: "feature/demo"},
		// No per-line branch: the header's branch applies, like the legacy tool.
		// Resolved by project key, since its source dir lives elsewhere.
		{Alias: "web", Project: "web", SourceDir: "/elsewhere/Some.Web", Branch: "feature/demo"},
	}
	if len(ws.Repos) != len(want) {
		t.Fatalf("Repos = %+v, want %+v", ws.Repos, want)
	}
	for i := range want {
		if ws.Repos[i] != want[i] {
			t.Errorf("Repos[%d] = %+v, want %+v", i, ws.Repos[i], want[i])
		}
	}

	for _, w := range f.fs.Writes {
		if strings.Contains(string(w), "/.ws/") {
			t.Errorf("wrote %s: adoption must never write inside .ws/", w)
		}
	}
	data, _ := f.fs.ReadFile(root.Join(".ws", "workspace.conf"))
	if string(data) != demoConf {
		t.Errorf("legacy manifest changed")
	}
	if ok, _ := f.fs.Exists(root.Join(".ws", "workspace.conf")); !ok {
		t.Errorf("legacy manifest removed")
	}
}

func TestAdoptLegacyWorkspaces_IsIdempotentAndIgnoresNativeAndPlainDirectories(t *testing.T) {
	f := newAdoptFixture(t)
	f.legacy(t, "demo", demoConf, "api", "web")
	native := adoptRoot.Join("native")
	f.store.PutManifest(native, domain.Manifest{SchemaVersion: 1, Workspace: domain.Workspace{Name: "native", Root: native, Context: "other"}})
	_ = f.fs.MkdirAll(native)
	_ = f.fs.MkdirAll(adoptRoot.Join("plain"))
	_ = f.fs.MkdirAll(adoptRoot.Join(".ws-archive"))

	first := f.run(t)
	if len(first.Adopted) != 1 {
		t.Fatalf("first run Adopted = %+v, want only demo", first.Adopted)
	}
	second := f.run(t)
	if len(second.Adopted) != 0 || len(second.Skipped) != 1 || second.Skipped[0].Reason != messages.AdoptSkipAlreadyAdopted {
		t.Fatalf("second run = %+v, want demo reported as already adopted", second)
	}
	m, _ := f.store.LoadManifest(context.Background(), native)
	if m.Workspace.Context != "other" {
		t.Errorf("native manifest was rewritten: %+v", m.Workspace)
	}
}

func TestAdoptLegacyWorkspaces_ReportsEachProblemPerWorkspace(t *testing.T) {
	f := newAdoptFixture(t)
	good := f.legacy(t, "good", demoConf, "api", "web")
	f.legacy(t, "unresolved", "branch = b\n[repos]\napi|Some.Api|b\nx|Nobody.Knows|b\n", "api", "x")
	f.legacy(t, "empty", "branch = b\n[repos]\n")
	f.legacy(t, "noconfrepos", "branch = b\n")
	f.legacy(t, "detached", "[repos]\napi|Some.Api|\n", "api")
	f.legacy(t, "gone", "[repos]\napi|Some.Api|\n")
	f.legacy(t, "split", "[repos]\napi|Some.Api|one\nweb|web|two\n", "api", "web")
	f.git.CurrentBranchFunc = func(wt domain.Path) (domain.BranchName, bool, error) {
		return "", true, nil
	}

	res := f.run(t)

	if len(res.Adopted) != 1 || res.Adopted[0].Root != good {
		t.Fatalf("Adopted = %+v, want only good", res.Adopted)
	}
	wantReason := map[string]messages.Key{
		"unresolved":  messages.AdoptSkipUnresolvedProject,
		"empty":       messages.AdoptSkipNoRepos,
		"noconfrepos": messages.AdoptSkipNoRepos,
		"detached":    messages.AdoptSkipBranchUnknown,
		"gone":        messages.AdoptSkipBranchUnknown,
		"split":       messages.AdoptSkipBranchAmbiguous,
	}
	got := map[string]app.SkippedLegacyWorkspace{}
	for _, s := range res.Skipped {
		got[s.Root.Base()] = s
	}
	if len(got) != len(wantReason) {
		t.Fatalf("Skipped = %+v, want %d entries", res.Skipped, len(wantReason))
	}
	for name, reason := range wantReason {
		s, ok := got[name]
		if !ok || s.Reason != reason {
			t.Errorf("Skipped[%s] = %+v, want reason %s", name, s, reason)
			continue
		}
		if _, err := f.store.LoadManifest(context.Background(), adoptRoot.Join(name)); err == nil {
			t.Errorf("%s: a skipped workspace must get no manifest", name)
		}
		if s.Message() == "" || strings.Contains(s.Message(), "%!") {
			t.Errorf("%s: Message() = %q", name, s.Message())
		}
	}
	if got["unresolved"].Detail != "Nobody.Knows" {
		t.Errorf("unresolved Detail = %q, want the project name", got["unresolved"].Detail)
	}
}

func TestAdoptLegacyWorkspaces_DerivesTheBranchFromGitWhenTheManifestLacksIt(t *testing.T) {
	f := newAdoptFixture(t)
	root := f.legacy(t, "derived", "[repos]\napi|Some.Api|\nweb|Some.Web|\n", "api", "web")
	f.git.CurrentBranchFunc = func(wt domain.Path) (domain.BranchName, bool, error) {
		return "feature/x", false, nil
	}

	res := f.run(t)
	if len(res.Adopted) != 1 {
		t.Fatalf("result = %+v, want derived adopted", res)
	}
	m, _ := f.store.LoadManifest(context.Background(), root)
	if m.Workspace.Branch != "feature/x" {
		t.Errorf("Branch = %q, want feature/x", m.Workspace.Branch)
	}
	for _, r := range m.Workspace.Repos {
		if r.Branch != "feature/x" {
			t.Errorf("repo %s branch = %q, want feature/x", r.Alias, r.Branch)
		}
	}
	// No base_branch in the legacy manifest: the context's own resolved
	// default applies, exactly as the legacy tool falls back to its config.
	if m.Workspace.Options.BaseBranch == nil || *m.Workspace.Options.BaseBranch != "main" {
		t.Errorf("Options.BaseBranch = %v, want the context default main", m.Workspace.Options.BaseBranch)
	}
	if !m.Workspace.Created.IsZero() {
		t.Errorf("Created = %v, want zero (never invented)", m.Workspace.Created)
	}
}

func TestAdoptLegacyWorkspaces_UnreadableExistingManifestIsReportedNotOverwritten(t *testing.T) {
	f := newAdoptFixture(t)
	f.legacy(t, "demo", demoConf, "api", "web")
	f.store.LoadManifestErr = errors.New("corrupt yaml")

	res := f.run(t)
	if len(res.Adopted) != 0 || len(res.Skipped) != 1 || res.Skipped[0].Reason != messages.AdoptSkipManifestUnreadable {
		t.Fatalf("result = %+v, want one manifest_unreadable skip", res)
	}
}

func TestAdoptLegacyWorkspaces_WriteFailureIsReportedPerWorkspace(t *testing.T) {
	f := newAdoptFixture(t)
	f.legacy(t, "demo", demoConf, "api", "web")
	f.store.SaveManifestErr = errors.New("disk full")

	res := f.run(t)
	if len(res.Skipped) != 1 || res.Skipped[0].Reason != messages.AdoptSkipWriteFailed || res.Skipped[0].Detail != "disk full" {
		t.Fatalf("result = %+v, want one write_failed skip", res)
	}
}

func TestAdoptLegacyWorkspaces_MissingWorkspacesRootIsEmptyNotAnError(t *testing.T) {
	f := newAdoptFixture(t)
	f.ctx.WorkspacesRoot = "/does/not/exist"
	res := f.run(t)
	if len(res.Adopted) != 0 || len(res.Skipped) != 0 {
		t.Fatalf("result = %+v, want empty", res)
	}
}

func TestRenderAdoptSummary(t *testing.T) {
	lines := app.RenderAdoptSummary(app.AdoptLegacyWorkspacesResult{
		Adopted: []app.AdoptedLegacyWorkspace{{Name: "demo", Root: "/w/demo"}},
		Skipped: []app.SkippedLegacyWorkspace{{Root: "/w/x", Reason: messages.AdoptSkipUnresolvedProject, Detail: "Nobody"}},
	})
	joined := strings.Join(lines, "\n")
	for _, want := range []string{"demo", "/w/x", "Nobody"} {
		if !strings.Contains(joined, want) {
			t.Errorf("summary %q missing %q", joined, want)
		}
	}
	if strings.Contains(joined, "%!") {
		t.Errorf("summary has a formatting error: %q", joined)
	}
	if empty := app.RenderAdoptSummary(app.AdoptLegacyWorkspacesResult{}); len(empty) != 1 {
		t.Errorf("empty summary = %q, want one 'nothing to adopt' line", empty)
	}
}

// TestAdoptLegacyWorkspaces_RecordsAPerRepoBaseWhenTheWorkspaceBaseIsAbsent:
// a repo with no branch named like the workspace base gets its own base
// recorded (the remote default here), so status compares it sensibly; a
// repo that has the workspace base records nothing.
func TestAdoptLegacyWorkspaces_RecordsAPerRepoBaseWhenTheWorkspaceBaseIsAbsent(t *testing.T) {
	f := newAdoptFixture(t)
	root := f.legacy(t, "demo", demoConf, "api", "web")
	f.git.ResolveBaseFunc = func(repo domain.Path, remote string, b domain.BranchName) (ports.BaseRef, error) {
		if repo == "/elsewhere/Some.Web" && b != "master" {
			return ports.BaseRef{Ref: "HEAD"}, nil
		}
		return ports.BaseRef{Ref: remote + "/" + string(b), Remote: true}, nil
	}
	f.git.RemoteDefaultBranchFunc = func(repo domain.Path, _ string) (domain.BranchName, bool, error) {
		return "master", true, nil
	}

	if res := f.run(t); len(res.Adopted) != 1 {
		t.Fatalf("result = %+v, want demo adopted", res)
	}

	m, err := f.store.LoadManifest(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	got := map[string]domain.BranchName{}
	for _, r := range m.Workspace.Repos {
		got[r.Alias] = r.BaseBranch
	}
	if got["api"] != "" || got["web"] != "master" {
		t.Fatalf("per-repo bases = %v, want api unrecorded (has develop) and web=master", got)
	}
}

// TestAdoptLegacyWorkspaces_ExistingManifestOwnershipIsDistinguished: a
// legacy folder that already has a wspace manifest is reported as adopted
// by this context, left alone when another existing context owns it, and
// claimed when its owner context no longer exists.
func TestAdoptLegacyWorkspaces_ExistingManifestOwnershipIsDistinguished(t *testing.T) {
	f := newAdoptFixture(t)
	f.store.PutContext(f.ctx)
	f.store.PutContext(domain.Context{Name: "acme", WorkspacesRoot: adoptRoot})
	seed := func(name string, owner domain.ContextName) domain.Path {
		root := f.legacy(t, name, demoConf, "api", "web")
		f.store.PutManifest(root, domain.Manifest{SchemaVersion: 1, Workspace: domain.Workspace{Name: name, Root: root, Context: owner, Branch: "b"}})
		return root
	}
	seed("own", "work")
	seed("theirs", "acme")
	orphan := seed("findings", "legacy")

	res := f.run(t)
	if len(res.Adopted) != 0 {
		t.Fatalf("Adopted = %+v, want none", res.Adopted)
	}
	want := map[domain.Path]struct {
		reason messages.Key
		detail string
	}{
		adoptRoot.Join("own"):    {messages.AdoptSkipAlreadyAdopted, "work"},
		adoptRoot.Join("theirs"): {messages.AdoptSkipOwnedByOther, "acme"},
		orphan:                   {messages.AdoptSkipOrphanClaimed, "legacy"},
	}
	if len(res.Skipped) != len(want) {
		t.Fatalf("Skipped = %+v", res.Skipped)
	}
	for _, s := range res.Skipped {
		w := want[s.Root]
		if s.Reason != w.reason || s.Detail != w.detail {
			t.Errorf("skip %s = %s(%s), want %s(%s)", s.Root, s.Reason, s.Detail, w.reason, w.detail)
		}
		if strings.Contains(s.Message(), "%!") {
			t.Errorf("message %q", s.Message())
		}
	}
	m, _ := f.store.LoadManifest(context.Background(), orphan)
	if m.Workspace.Context != "work" || m.Workspace.Branch != "b" {
		t.Errorf("orphan manifest = %+v, want claimed by work with other fields kept", m.Workspace)
	}
	t2, _ := f.store.LoadManifest(context.Background(), adoptRoot.Join("theirs"))
	if t2.Workspace.Context != "acme" {
		t.Errorf("theirs stolen: %+v", t2.Workspace)
	}
}
