// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Kivora Digital S.L.

package domain_test

import (
	"testing"
	"time"

	"github.com/kivoradigital/wspace/internal/domain"
)

// legacyWorkspaceConfSample is byte-for-byte the shape the legacy bash
// tool's own "create" command writes to "<workspace>/.ws/workspace.conf".
const legacyWorkspaceConfSample = `# ws workspace manifest - regenerated by ws, edit with ws add/rm
name = demo
created = 2025-03-04T05:06:07Z
projects_root = /abs/projects
base_branch = develop
branch = feature/demo
copy_env = yes

[repos]
api|Some.Api|feature/demo
web|Some.Web|feature/demo
`

func hasLegacyIssue(issues []domain.LegacyIssue, key string, reason domain.LegacyReason) bool {
	for _, i := range issues {
		if i.Key == key && i.Reason == reason {
			return true
		}
	}
	return false
}

func TestParseLegacyWorkspaceConf_FullSample(t *testing.T) {
	got := domain.ParseLegacyWorkspaceConf([]byte(legacyWorkspaceConfSample))

	if got.Name != "demo" {
		t.Errorf("Name = %q, want demo", got.Name)
	}
	wantCreated := time.Date(2025, 3, 4, 5, 6, 7, 0, time.UTC)
	if !got.Created.Equal(wantCreated) {
		t.Errorf("Created = %v, want %v", got.Created, wantCreated)
	}
	if got.ProjectsRoot != "/abs/projects" {
		t.Errorf("ProjectsRoot = %q, want /abs/projects", got.ProjectsRoot)
	}
	if got.BaseBranch == nil || *got.BaseBranch != "develop" {
		t.Errorf("BaseBranch = %v, want develop", got.BaseBranch)
	}
	if got.Branch != "feature/demo" {
		t.Errorf("Branch = %q, want feature/demo", got.Branch)
	}
	if got.CopyEnv == nil || !*got.CopyEnv {
		t.Errorf("CopyEnv = %v, want true", got.CopyEnv)
	}
	want := []domain.LegacyWorkspaceRepo{
		{Alias: "api", Project: "Some.Api", Branch: "feature/demo"},
		{Alias: "web", Project: "Some.Web", Branch: "feature/demo"},
	}
	if len(got.Repos) != len(want) {
		t.Fatalf("Repos = %+v, want %+v", got.Repos, want)
	}
	for i := range want {
		if got.Repos[i] != want[i] {
			t.Errorf("Repos[%d] = %+v, want %+v", i, got.Repos[i], want[i])
		}
	}
	if len(got.Issues) != 0 {
		t.Errorf("Issues = %+v, want none", got.Issues)
	}
}

func TestParseLegacyWorkspaceConf_EdgeCases(t *testing.T) {
	tests := []struct {
		name  string
		src   string
		check func(t *testing.T, got domain.LegacyWorkspaceConf)
	}{
		{
			name: "CRLF line endings are tolerated",
			src:  "name = demo\r\nbranch = feat\r\ncopy_env = no\r\n\r\n[repos]\r\napi|Api|feat\r\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if got.Name != "demo" || got.Branch != "feat" {
					t.Errorf("Name/Branch = %q/%q, want demo/feat", got.Name, got.Branch)
				}
				if got.CopyEnv == nil || *got.CopyEnv {
					t.Errorf("CopyEnv = %v, want false", got.CopyEnv)
				}
				if len(got.Repos) != 1 || got.Repos[0] != (domain.LegacyWorkspaceRepo{Alias: "api", Project: "Api", Branch: "feat"}) {
					t.Errorf("Repos = %+v", got.Repos)
				}
				if len(got.Issues) != 0 {
					t.Errorf("Issues = %+v, want none", got.Issues)
				}
			},
		},
		{
			name: "missing keys stay absent, never defaulted",
			src:  "[repos]\napi|Api|\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if got.Name != "" || got.Branch != "" || got.BaseBranch != nil || got.CopyEnv != nil || got.ProjectsRoot != "" {
					t.Errorf("got %+v, want every header field absent", got)
				}
				if !got.Created.IsZero() {
					t.Errorf("Created = %v, want zero", got.Created)
				}
				if len(got.Repos) != 1 || got.Repos[0].Branch != "" {
					t.Errorf("Repos = %+v, want one repo with an empty branch", got.Repos)
				}
			},
		},
		{
			name: "comments and blank lines are skipped in both sections",
			src:  "# header\n  # indented comment\nbranch = b1\n\n[repos]\n# a comment\n   \napi|Api|b1\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if got.Branch != "b1" || len(got.Repos) != 1 || len(got.Issues) != 0 {
					t.Errorf("got %+v", got)
				}
			},
		},
		{
			name: "matching surrounding quotes are stripped",
			src:  "name = \"demo\"\nbranch = 'feat/x'\n[repos]\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if got.Name != "demo" || got.Branch != "feat/x" {
					t.Errorf("Name/Branch = %q/%q, want demo/feat/x", got.Name, got.Branch)
				}
			},
		},
		{
			name: "an unbalanced quote is kept literally, exactly as the legacy reader does",
			src:  "name = \"demo\n[repos]\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if got.Name != "\"demo" {
					t.Errorf("Name = %q, want the literal value", got.Name)
				}
			},
		},
		{
			name: "duplicate keys resolve last-write-wins like the legacy reader",
			src:  "branch = one\nbranch = two\n[repos]\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if got.Branch != "two" {
					t.Errorf("Branch = %q, want two", got.Branch)
				}
			},
		},
		{
			name: "invalid values are reported and treated as absent",
			src:  "created = yesterday\nbase_branch = bad branch\ncopy_env = maybe\nprojects_root = relative/path\n[repos]\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				for _, key := range []string{"created", "base_branch", "copy_env", "projects_root"} {
					if !hasLegacyIssue(got.Issues, key, domain.LegacyReasonInvalidValue) {
						t.Errorf("Issues = %+v, want invalid %s", got.Issues, key)
					}
				}
				if !got.Created.IsZero() || got.BaseBranch != nil || got.CopyEnv != nil || got.ProjectsRoot != "" {
					t.Errorf("got %+v, want every invalid field absent", got)
				}
			},
		},
		{
			name: "unknown keys and malformed header lines are reported",
			src:  "future_key = 1\njust some words\n[repos]\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if !hasLegacyIssue(got.Issues, "future_key", domain.LegacyReasonUnknownKey) {
					t.Errorf("Issues = %+v, want unknown future_key", got.Issues)
				}
				if !hasLegacyIssue(got.Issues, "just some words", domain.LegacyReasonMalformedLine) {
					t.Errorf("Issues = %+v, want malformed line", got.Issues)
				}
			},
		},
		{
			name: "missing repos section is reported",
			src:  "name = demo\nbranch = feat\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if len(got.Repos) != 0 {
					t.Errorf("Repos = %+v, want none", got.Repos)
				}
				if !hasLegacyIssue(got.Issues, "[repos]", domain.LegacyReasonMissingReposSection) {
					t.Errorf("Issues = %+v, want missing [repos]", got.Issues)
				}
			},
		},
		{
			name: "malformed repo lines are reported, never guessed",
			src:  "[repos]\nonlyalias\n|Api|b\napi||b\na|b|c|d\nok|Ok|\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if len(got.Repos) != 1 || got.Repos[0] != (domain.LegacyWorkspaceRepo{Alias: "ok", Project: "Ok"}) {
					t.Errorf("Repos = %+v, want only ok|Ok", got.Repos)
				}
				for _, line := range []string{"onlyalias", "|Api|b", "api||b", "a|b|c|d"} {
					if !hasLegacyIssue(got.Issues, line, domain.LegacyReasonMalformedLine) {
						t.Errorf("Issues = %+v, want malformed %q", got.Issues, line)
					}
				}
			},
		},
		{
			name: "an invalid per-repo branch is reported and left empty",
			src:  "[repos]\napi|Api|bad branch\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if len(got.Repos) != 1 || got.Repos[0].Branch != "" {
					t.Errorf("Repos = %+v, want api with an empty branch", got.Repos)
				}
				if !hasLegacyIssue(got.Issues, "api|Api|bad branch", domain.LegacyReasonInvalidValue) {
					t.Errorf("Issues = %+v, want invalid repo branch", got.Issues)
				}
			},
		},
		{
			name: "an alias that is not a single folder name is malformed",
			src:  "[repos]\n../x|Api|b\n.ws|Api|b\n",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if len(got.Repos) != 0 {
					t.Errorf("Repos = %+v, want none", got.Repos)
				}
				if !hasLegacyIssue(got.Issues, "../x|Api|b", domain.LegacyReasonMalformedLine) ||
					!hasLegacyIssue(got.Issues, ".ws|Api|b", domain.LegacyReasonMalformedLine) {
					t.Errorf("Issues = %+v, want both lines malformed", got.Issues)
				}
			},
		},
		{
			name: "empty input",
			src:  "",
			check: func(t *testing.T, got domain.LegacyWorkspaceConf) {
				if len(got.Repos) != 0 || !hasLegacyIssue(got.Issues, "[repos]", domain.LegacyReasonMissingReposSection) {
					t.Errorf("got %+v", got)
				}
			},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tt.check(t, domain.ParseLegacyWorkspaceConf([]byte(tt.src)))
		})
	}
}
